swagger: "2.0"
info:
  description: "Образец документации для wordpress плагина"
  version: "0.0.1"
  title: "Travelpayouts wp"
basePath: "/"
tags:
- name: "Глобальные настройки"
  description: "Настройки пользователя, которые будут использованы всеми виджетами/шорткодами"
schemes:
- "https"
- "http"
paths:
  /account:
    post:
      tags:
      - "Глобальные настройки"
      description: "Сохранение информации о учетных записях пользователя"
      responses:
        404:
          description: "В разработке"
  /settings:
    get:
      tags:
        - "Глобальные настройки"  
      responses:
        200:
          description: "Отображаем аттрибуты формы с данными"
          schema:
           $ref: "#/definitions/Settings"
    post:
      tags:
      - "Глобальные настройки"
      description: "Сохранение информации о настройках пользователя"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        404:
          description: "В разработке"
        500:
          description: "Мы все потеряли"
        200:
          description: "Данные успешно сохранены"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/Settings"
definitions:
  Settings:
    type: "object"
    properties:
      flights_source:
        type: "string"
        description: "Хост для авиабилетов"
        default: "???"
        format: "selectBox"
        
      hotels_source:
        type: "string"
        description: "Хост для отелей"
        default: "???"
        format: "input"
      language:
        type: "string"
        description: "Язык таблиц и виджетов"
        default: "???"
      currency:
        type: "string"
        description: "Код валюты"
        default: "???"
      script_location:
        type: "string"
        description: "Размещение скриптов плагина внутри тега"
        enum: 
          - "<head>"
          - "<div>"
        default: "<head>"
      render_everywere:
        type: "boolean"
        description: "Размещение таблиц вне постовых страниц. Для оптимизации работы вашего сайта скрипты плагина по умолчанию вызываются только если шорткоды вставлены в постах или страницах. Активируйте эту опцию, если вы хотите размещать шорткоды в других местах (например, сайдбар)"
        default: false
