swagger: '2.0'
info:
  description: 'Образец документации для wordpress плагина'
  version: '0.0.4'
  title: 'Travelpayouts wordpress plugin'
basePath: '/wp-admin/admin-ajax.php?action=travelpayouts&page='
schemes:
  - 'https'
  - 'http'
paths:
  /account:
    $ref: './pages/account.yaml#/paths/account'
  /settings:
    $ref: './pages/settings.yaml#/paths/settings'
  /shortcode/flights/tp_cheapest_flights_shortcodes:
    $ref: './shortcodes/flights.yaml#/paths/tp_cheapest_flights_shortcodes'
  /shortcode/flights/tp_cheapest_ticket_each_day_month_shortcodes:
    $ref: './shortcodes/flights.yaml#/paths/tp_cheapest_ticket_each_day_month_shortcodes'
  /shortcode/flights/tp_cheapest_tickets_each_month_shortcodes:
    $ref: './shortcodes/flights.yaml#/paths/tp_cheapest_tickets_each_month_shortcodes'
  /shortcode/flights/tp_direct_flights_shortcodes:
    $ref: './shortcodes/flights.yaml#/paths/tp_direct_flights_shortcodes'
  /shortcode/flights/tp_direct_flights_route_shortcodes:
    $ref: './shortcodes/flights.yaml#/paths/tp_direct_flights_route_shortcodes'
  /shortcode/flights/tp_from_our_city_fly_shortcodes:
    $ref: './shortcodes/flights.yaml#/paths/tp_from_our_city_fly_shortcodes'
  /shortcode/flights/tp_in_our_city_fly_shortcodes:
    $ref: './shortcodes/flights.yaml#/paths/tp_in_our_city_fly_shortcodes'
  /shortcode/flights/tp_our_site_search_shortcodes:
    $ref: './shortcodes/flights.yaml#/paths/tp_our_site_search_shortcodes'
  /shortcode/flights/tp_popular_destinations_airlines_shortcodes:
    $ref: './shortcodes/flights.yaml#/paths/tp_popular_destinations_airlines_shortcodes'
  /shortcode/flights/tp_popular_routes_from_city_shortcodes:
    $ref: './shortcodes/flights.yaml#/paths/tp_popular_routes_from_city_shortcodes'
  /shortcode/flights/tp_price_calendar_month_shortcodes:
    $ref: './shortcodes/flights.yaml#/paths/tp_price_calendar_month_shortcodes'
  /shortcode/flights/tp_price_calendar_week_shortcodes:
    $ref: './shortcodes/flights.yaml#/paths/tp_price_calendar_week_shortcodes'
  /shortcode/hotels/tp_hotels_selections_discount_shortcodes:
    $ref: './shortcodes/hotels.yaml#/paths/tp_hotels_selections_discount_shortcodes'
  /shortcode/hotels/tp_hotels_selections_date_shortcodes:
    $ref: './shortcodes/hotels.yaml#/paths/tp_hotels_selections_date_shortcodes'

#  Виджеты
# Перелеты
  /shortcode/flights/tp_map_widget:
    $ref: './shortcodes/widgets/flights.yaml#/paths/tp_map_widget'
  /shortcode/flights/tp_calendar_widget:
    $ref: './shortcodes/widgets/flights.yaml#/paths/tp_calendar_widget'
  /shortcode/flights/tp_subscriptions_widget:
    $ref: './shortcodes/widgets/flights.yaml#/paths/tp_subscriptions_widget'
  /shortcode/flights/tp_popular_routes_widget:
    $ref: './shortcodes/widgets/flights.yaml#/paths/tp_popular_routes_widget'
  /shortcode/flights/tp_ducklett_widget:
    $ref: './shortcodes/widgets/flights.yaml#/paths/tp_ducklett_widget'
# Отели
  /shortcode/hotels/tp_hotelmap_widget:
    $ref: './shortcodes/widgets/hotels.yaml#/paths/tp_hotelmap_widget'
  /shortcode/hotels/tp_hotel_widget:
    $ref: './shortcodes/widgets/hotels.yaml#/paths/tp_hotel_widget'
  /shortcode/hotels/tp_hotel_selections_widget:
    $ref: './shortcodes/widgets/hotels.yaml#/paths/tp_hotel_selections_widget'
# Железные дороги
  /shortcode/railway/tp_tutu:
    $ref: './shortcodes/railway.yaml#/paths/tp_tutu'
# Поисковые формы
  /search_forms:
    $ref: './shortcodes/search.yaml#/paths/search_forms'
  /search_forms/{id}:
    $ref: './shortcodes/search.yaml#/paths/search_forms_edit'
definitions:
  adminConfiguration:
    type: object
    description: >
      Модели, которые будут использованы при конфигурации таблиц/виджетов в админ панели
    properties:
      settings:
        $ref: './pages/settings.yaml#/models/settings'
      account:
        $ref: './pages/account.yaml#/models/account'
      flightsShortcodes:
        $ref: './shortcodes/flights.yaml#/models'
      hotelsShortcodes:
        $ref: './shortcodes/hotels.yaml#/models'
      widgetsShortcodes:
        type: object
        description: 'Шорткоды виджетов'
        properties:
          flights:
            $ref: './shortcodes/widgets/flights.yaml#/models'
          hotels:
            $ref: './shortcodes/widgets/hotels.yaml#/models'
      searchForm:
        $ref: './shortcodes/search.yaml#/models'
      railwayShortcodes:
        $ref: './shortcodes/railway.yaml#/models'
  shortcodesWindow:
    type: object
    description: >
      Модели, которые будут использованы при вставке шорткодов
    properties:
      flights:
        $ref: './shortcodes_window/flights.yaml#/models'
      hotels:
        $ref: './shortcodes_window/hotels.yaml#/models'
      railway:
        $ref: './shortcodes_window/railway.yaml#/models'

