swagger: "2.0"
info:
  description: "Образец документации для wordpress плагина"
  version: "0.0.1"
  title: "Travelpayouts wp"
basePath: "/"
tags:
- name: "Глобальные настройки"
  description: "Настройки пользователя, которые будут использованы всеми виджетами/шорткодами"
schemes:
- "https"
- "http"
paths:
  /account:
    get:
      tags:
      - "Глобальные настройки"
      - "Аккаунт"
      description: "Отображение информации о учетных записях пользователя"
      responses:
        200:
          description: "Отображаем аттрибуты формы с данными"
          schema:
           $ref: "#/definitions/Account"
    post:
      tags:
      - "Глобальные настройки"
      - "Аккаунт"
      description: "Сохранение информации о учетных записях пользователя"
      responses:
        404:
          description: "В разработке"
        200:
          description: "Данные успешно сохранены"
          schema:
            $ref: "#/definitions/ApiResponse"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/Account"
  /settings:
    get:
      tags:
        - "Глобальные настройки"
        - "Настройки"
      responses:
        200:
          description: "Отображаем аттрибуты формы с данными"
          schema:
           $ref: "#/definitions/Settings"
    post:
      tags:
      - "Глобальные настройки"
      - "Настройки"
      description: "Сохранение информации о настройках пользователя"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        404:
          description: "В разработке"
        200:
          description: "Данные успешно сохранены"
          schema:
            $ref: "#/definitions/ApiResponse"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/Settings"
definitions:
  Settings:
    type: "object"
    properties:
      flights_source:
        type: "string"
        description: "Хост для авиабилетов"
        default: "???"
        format: "selectBox"
      hotels_source:
        type: "string"
        description: "Хост для отелей"
        default: "???"
        format: "selectBox"
      language:
        type: "string"
        description: "Язык таблиц и виджетов"
        default: "???"
        format: "selectBox"
      currency:
        type: "string"
        description: "Код валюты"
        default: "???"
        format: "selectBox"
      script_location:
        type: "string"
        description: "Размещение скриптов плагина внутри тега"
        enum: 
          - "<head>"
          - "<div>"
        default: "<head>"
        format: "selectBox"
      render_everywere:
        type: "boolean"
        description: "Размещение таблиц вне постовых страниц. Для оптимизации работы вашего сайта скрипты плагина по умолчанию вызываются только если шорткоды вставлены в постах или страницах. Активируйте эту опцию, если вы хотите размещать шорткоды в других местах (например, сайдбар)"
        default: false
        format: "checkbox"
  Account:
    type: "object"
    properties:
      api_token:
        type: "string"
        description: "Ваш API токен Travelpayouts"
        format: "input"
      api_marker:
        type: "string"
        description: "Ваш партнёрский маркер Travelpayouts"
        format: "input"
      flights_domain:
        type: "string"
        description: "АВИА WHITE LABEL"
        format: "input"
      hotels_domain:
        type: "string"
        description: "ОТЕЛЬНЫЙ WHITE LABEL"
        format: "input"
    required: 
      - "api_token"
      - "api_marker"
  ApiResponse:
    type: "object"
    properties:
      status: 
        type: "string"
        description: "Статус ответа"
        enum:
          - "ok"
          - "error"
      messages:
        type: "string"
        description: "Массив сообщений о том, что что-то пошло не так, отображаем в случае, если status === error"
      data:
        type: "object"
        description: "Необходимые данные"
