swagger: '2.0'
info:
  description: 'Образец документации для wordpress плагина'
  version: '0.0.2'
  title: 'Travelpayouts wp'
basePath: '/wp-admin/admin-ajax.php?action=travelpayouts&page='
schemes:
  - 'https'
  - 'http'
paths:
  /account:
    $ref: './pages/account.yaml#/paths/account'
  /settings:
    $ref: './pages/settings.yaml#/paths/settings'
  /shortcode/flights/tp_cheapest_flights_shortcodes:
    $ref: './shortcodes/flights.yaml#/paths/tp_cheapest_flights_shortcodes'
  /shortcode/flights/tp_cheapest_ticket_each_day_month_shortcodes:
    $ref: './shortcodes/flights.yaml#/paths/tp_cheapest_ticket_each_day_month_shortcodes'
  /shortcode/flights/tp_cheapest_tickets_each_month_shortcodes:
    $ref: './shortcodes/flights.yaml#/paths/tp_cheapest_tickets_each_month_shortcodes'
  /shortcode/flights/tp_direct_flights_shortcodes:
    $ref: './shortcodes/flights.yaml#/paths/tp_direct_flights_shortcodes'
  /shortcode/flights/tp_direct_flights_route_shortcodes:
    $ref: './shortcodes/flights.yaml#/paths/tp_direct_flights_route_shortcodes'
  /shortcode/flights/tp_from_our_city_fly_shortcodes:
    $ref: './shortcodes/flights.yaml#/paths/tp_from_our_city_fly_shortcodes'
  /shortcode/flights/tp_in_our_city_fly_shortcodes:
    $ref: './shortcodes/flights.yaml#/paths/tp_in_our_city_fly_shortcodes'
  /shortcode/flights/tp_our_site_search_shortcodes:
    $ref: './shortcodes/flights.yaml#/paths/tp_our_site_search_shortcodes'
  /shortcode/flights/tp_popular_destinations_airlines_shortcodes:
    $ref: './shortcodes/flights.yaml#/paths/tp_popular_destinations_airlines_shortcodes'
  /shortcode/flights/tp_popular_routes_from_city_shortcodes:
    $ref: './shortcodes/flights.yaml#/paths/tp_popular_routes_from_city_shortcodes'
  /shortcode/flights/tp_price_calendar_month_shortcodes:
    $ref: './shortcodes/flights.yaml#/paths/tp_price_calendar_month_shortcodes'
  /shortcode/flights/tp_price_calendar_week_shortcodes:
    $ref: './shortcodes/flights.yaml#/paths/tp_price_calendar_week_shortcodes'
  /shortcode/hotels/tp_hotels_selections_discount_shortcodes:
    $ref: './shortcodes/hotels.yaml#/paths/tp_hotels_selections_discount_shortcodes'
  /shortcode/hotels/tp_hotels_selections_date_shortcodes:
    $ref: './shortcodes/hotels.yaml#/paths/tp_hotels_selections_date_shortcodes'
definitions:
  settings:
    $ref: './pages/settings.yaml#/models/settings'
  account:
    $ref: './pages/account.yaml#/models/account'
# Модели таблиц перелетов
  tp_cheapest_flights_shortcodes:
    $ref: './shortcodes/flights.yaml#/models/tp_cheapest_flights_shortcodes'
  tp_cheapest_ticket_each_day_month_shortcodes:
    $ref: './shortcodes/flights.yaml#/models/tp_cheapest_ticket_each_day_month_shortcodes'
  tp_cheapest_tickets_each_month_shortcodes:
    $ref: './shortcodes/flights.yaml#/models/tp_cheapest_tickets_each_month_shortcodes'
  tp_direct_flights_shortcodes:
    $ref: './shortcodes/flights.yaml#/models/tp_direct_flights_shortcodes'
  tp_direct_flights_route_shortcodes:
    $ref: './shortcodes/flights.yaml#/models/tp_direct_flights_route_shortcodes'
  tp_from_our_city_fly_shortcodes:
    $ref: './shortcodes/flights.yaml#/models/tp_from_our_city_fly_shortcodes'
  tp_in_our_city_fly_shortcodes:
    $ref: './shortcodes/flights.yaml#/models/tp_in_our_city_fly_shortcodes'
  tp_our_site_search_shortcodes:
    $ref: './shortcodes/flights.yaml#/models/tp_our_site_search_shortcodes'
  tp_popular_destinations_airlines_shortcodes:
    $ref: './shortcodes/flights.yaml#/models/tp_popular_destinations_airlines_shortcodes'
  tp_popular_routes_from_city_shortcodes:
    $ref: './shortcodes/flights.yaml#/models/tp_popular_routes_from_city_shortcodes'
  tp_price_calendar_month_shortcodes:
    $ref: './shortcodes/flights.yaml#/models/tp_price_calendar_month_shortcodes'
  tp_price_calendar_week_shortcodes:
    $ref: './shortcodes/flights.yaml#/models/tp_price_calendar_week_shortcodes'
# Модели таблиц отелей
  tp_hotels_selections_date_shortcodes:
    $ref: './shortcodes/hotels.yaml#/models/tp_hotels_selections_date_shortcodes'
  tp_hotels_selections_discount_shortcodes:
    $ref: './shortcodes/hotels.yaml#/models/tp_hotels_selections_discount_shortcodes'
